name: Deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout:@v2
      - name: build angular
        run: |
          docker build ./ClientApp -t angular
    # - name: pack angular
