name: Deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build angular
        run: |
          docker build ./ClientApp -t angular

      - name: save angular
        run: |
          docker save -o angular.tar angular
          
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.REMOTE_HOST }}

      - name: rsync over ssh
        run: rsync angular.tar docker-compose.yml root@remote:~/
#       - name: send
#         uses: garygrossgarten/github-action-scp@release
#         with:
#           local: angular.tar docker-compose.yml
#           remote: ./
#           host: ${{ secrets.REMOTE_HOST }}
#           username: ${{ secrets.SSH_USER }}
#           password: ${{ secrets.PASSWORD }}
