name: Deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: create dist
        run: |
          mkdir dist
        
      - name: build angular
        run: |
          docker build ./ClientApp -t angular
        
      - name: save angular
        run: |
          docker save -o ./dist/angular.tar angular
          
      - name: copy folder to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: ./dist
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          
      - name: remove local folder
        run: |
           rm -rf ./dist
           
      - name: run script on server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ./deploy.sh
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}

